// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8OcMspWbRP9HnEnGyqBJyK7VoaVUB8A',
    appId: '1:163507366913:web:554aaeb85ec120c8836400',
    messagingSenderId: '163507366913',
    projectId: 'flpaintapp-49429',
    authDomain: 'flpaintapp-49429.firebaseapp.com',
    storageBucket: 'flpaintapp-49429.firebasestorage.app',
    measurementId: 'G-29WTWETP5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDpSN9e84DOiFb4dqhzVq-0pNZVNaLzK4',
    appId: '1:163507366913:android:b15070b2e73a98a3836400',
    messagingSenderId: '163507366913',
    projectId: 'flpaintapp-49429',
    storageBucket: 'flpaintapp-49429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABB6NBbyoSu--EjxSEZfU9b6LD4mOQMqk',
    appId: '1:163507366913:ios:331b4fc4be6e1ff0836400',
    messagingSenderId: '163507366913',
    projectId: 'flpaintapp-49429',
    storageBucket: 'flpaintapp-49429.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABB6NBbyoSu--EjxSEZfU9b6LD4mOQMqk',
    appId: '1:163507366913:ios:331b4fc4be6e1ff0836400',
    messagingSenderId: '163507366913',
    projectId: 'flpaintapp-49429',
    storageBucket: 'flpaintapp-49429.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn8OcMspWbRP9HnEnGyqBJyK7VoaVUB8A',
    appId: '1:163507366913:web:d703d123caadec20836400',
    messagingSenderId: '163507366913',
    projectId: 'flpaintapp-49429',
    authDomain: 'flpaintapp-49429.firebaseapp.com',
    storageBucket: 'flpaintapp-49429.firebasestorage.app',
    measurementId: 'G-Y271RT5BPS',
  );
}
